Lab5AspNetMVC/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business_Logic_Layer.Interfaces;
using Lab5AspNetMVC.Models;

namespace Lab5AspNetMVC.Controllers
{
    public class ReportsController : Controller
    {
        IReportsService reportsService;
        IDbCrud crudServ;

        public ReportsController(IReportsService reportservice, IDbCrud crudDb)
        {
            reportsService = reportservice;
            crudServ = crudDb;
        }


        [HttpGet]
        public ActionResult LinkReportKind()
        {
            return View(new LinkReportKindModel() { taskKindsList = crudServ.GetAllTaskKinds() });
        }

        [HttpPost]
        public ActionResult LinkReportKind(LinkReportKindModel model)
        {
            model.SelectionByKindData = reportsService.ReportSelectionByKind(model.SelectedKindId);
            model.taskKindsList = crudServ.GetAllTaskKinds();
            return View(model);
        }


        [HttpGet]
        public ActionResult LinkReportStatus()
        {
            return View(new LinkReportStatusModel() { taskStatusesList = crudServ.GetAllTaskStatuses() });
        }

        [HttpPost]
        public ActionResult LinkReportStatus(LinkReportStatusModel model)
        {
            model.SelectionByStatusData = reportsService.ReportSelectionByStatus(model.SelectedStatusId);
            model.taskStatusesList = crudServ.GetAllTaskStatuses();
            return View(model);
        }


        [HttpGet]
        public ActionResult SPReportRepeat()
        {
            return View(new SPReportRepeatModel());
        }

        [HttpPost]
        public ActionResult SPReportRepeat(SPReportRepeatModel  model)
        {
            model.SelectionByRepeatabilityData = reportsService.ReportSelectionByRepeatability(model.SelectedValueIsRepeat);
            return View(model);
        }





        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }
    }
}

Lab5AspNetMVC/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business_Logic_Layer.Interfaces;
using Lab5AspNetMVC.Models;

namespace Lab5AspNetMVC.Controllers
{
    public class TaskController : Controller
    {
        IDbCrud crudServ;

        public TaskController(IDbCrud crudServ)
        {
            this.crudServ = crudServ;
        }


        // Create

        [HttpGet]
        public ActionResult Create()
        {
            return View(new TaskModel(crudServ.GetAllTaskKinds(), crudServ.GetAllTaskStatuses()));
        }

        [HttpPost]
        public ActionResult Create(TaskModel model)
        {
            Business_Logic_Layer.DTO.TaskDTO t = new Business_Logic_Layer.DTO.TaskDTO();

            t.Id = model.Id;
            t.Name = model.Name;
            t.Description = model.Description;
            t.StatusId = model.StatusId;
            t.KindId = model.KindId;
            t.BeginDate = model.BeginDate;
            t.BeginTime = model.BeginTime;
            t.EndDate = model.EndDate;
            t.EndTime = model.EndTime;
            t.IsRepeat = model.IsRepeat;
            t.RepeatIntervalDays = model.RepeatIntervalDays;
            t.RepeatIntervalMonths = model.RepeatIntervalMonths;
            t.RepeatIntervalWeeks = model.RepeatIntervalWeeks;
            t.RepeatIntervalYears = model.RepeatIntervalYears;

            crudServ.CreateTask(t);

            return RedirectToAction("Index");
        }


        // GET: Task (Read)
        public ActionResult Index()
        {
            return View("Index", crudServ.GetAllTasks().Select(i => new TaskModel(i, crudServ.GetAllTaskKinds(), crudServ.GetAllTaskStatuses())));
        }

        // Update

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(new TaskModel(crudServ.GetTask(id), crudServ.GetAllTaskKinds(), crudServ.GetAllTaskStatuses()));
        }

        [HttpPost]
        public ActionResult Edit(TaskModel model)
        {
            Business_Logic_Layer.DTO.TaskDTO t = new Business_Logic_Layer.DTO.TaskDTO();

            t.Id = model.Id;
            t.Name = model.Name;
            t.Description = model.Description;
            t.StatusId = model.StatusId;
            t.KindId = model.KindId;
            t.BeginDate = model.BeginDate;
            t.BeginTime = model.BeginTime;
            t.EndDate = model.EndDate;
            t.EndTime = model.EndTime;
            t.IsRepeat = model.IsRepeat;
            t.RepeatIntervalDays = model.RepeatIntervalDays;
            t.RepeatIntervalMonths = model.RepeatIntervalMonths;
            t.RepeatIntervalWeeks = model.RepeatIntervalWeeks;
            t.RepeatIntervalYears = model.RepeatIntervalYears;

            crudServ.UpdateTask(t);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            crudServ.DeleteTask(id);
            return RedirectToAction("Index");
        }
    }
}

Lab5AspNetMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Задачи", "Index", "Task")</li>
                    <li>@Html.ActionLink("Выборка по виду", "LinkReportKind", "Reports")</li>
                    <li>@Html.ActionLink("Выборка по статусу", "LinkReportStatus", "Reports")</li>
                    <li>@Html.ActionLink("Выборка по повторяемости", "SPReportRepeat", "Reports")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now - Менеджер задач</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>